name: Build a zip & Comment on PR
on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  build-zip:
    name: "Build a zip and upload to server"
    runs-on: ubuntu-latest
    outputs:
      branch-name: ${{ steps.get-current-branch.outputs.branch_name }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: Extract current branch name
        id: get-current-branch
        run: echo "::set-output name=branch_name::$(REF=${GITHUB_HEAD_REF:-$GITHUB_REF} && echo ${REF#refs/heads/} | sed 's/\//-/g')"

      - name: Cache node modules
        id: cache-node
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Create a build
        run: npm run build

      - name: Build a package
        run: npm run build-zip

      - name: Create branch directory
        run: |
          cd artifact
          mkdir -p ${{ steps.get-current-branch.outputs.branch_name }}
          mv ultimate-addons-for-gutenberg.zip ${{ steps.get-current-branch.outputs.branch_name }}/

      - name: Upload a zip to server
        uses: burnett01/rsync-deployments@4.1
        with:
          # switches: -avzr --delete --delete-excluded --exclude-from=".distignore" --include="" --filter=""
          switches: -avzr
          path: ./artifact/
          remote_path: ${{ secrets.SSH_PATH }}
          remote_host: ${{ secrets.SSH_HOST }}
          remote_port: ${{ secrets.SSH_PORT }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_KEY }}

  comment-on-pr:
    name: Comment on PR with links to plugin ZIPs
    if: ${{ github.head_ref && github.head_ref != null }}
    runs-on: ubuntu-latest
    needs: build-zip
    env:
      CI: true
      GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
    outputs:
      pr_number: ${{ steps.get-pr-number.outputs.num }}
      comment_body: ${{ steps.get-comment-body.outputs.body }}
    steps:
      - name: Get PR number
        id: get-pr-number
        run: echo "::set-output name=num::$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')"

      - name: Check if a comment was already made
        id: find-comment
        uses: peter-evans/find-comment@v1
        with:
          issue-number: ${{ steps.get-pr-number.outputs.num }}
          comment-author: github-actions[bot]
          body-includes: Download the plugin [zip]

      - name: Get comment body
        id: get-comment-body
        run: |
          body="Plugin zip for ${{ github.event.pull_request.head.sha }} is ready :bellhop_bell:!
          - Download the plugin [zip](http://uag-dev.cvh6svsgwm-gok67yw2r652.p.runcloud.link/wp-content/uploads/uag-gh/${{ needs.build-zip.outputs.branch-name }}/ultimate-addons-for-gutenberg.zip)"
          body="${body//$'\n'/'%0A'}"
          echo "::set-output name=body::$body"
      - name: Create comment on PR with links to plugin zip
        if: ${{ steps.find-comment.outputs.comment-id == '' }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ steps.get-pr-number.outputs.num }}
          body: ${{ steps.get-comment-body.outputs.body }}

      - name: Update comment on PR with links to plugin zip
        if: ${{ steps.find-comment.outputs.comment-id != '' }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          edit-mode: replace
          body: ${{ steps.get-comment-body.outputs.body }}
